[project]
name = 'telepathic-ensemble-network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.brainwave-musical-translator]
path = 'contracts/brainwave-musical-translator.clar'
clarity_version = 3
epoch = 3.1

[contracts.neural-rhythm-synchronizer]
path = 'contracts/neural-rhythm-synchronizer.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
